# Use docker-based build environment (instead of openvz)
sudo: false

# Select JDKs >= Java 6 for testing
language: java
jdk:
  - oraclejdk8

# Test execution
install: true
script: "mvn -e -q clean compile test"
