# Use docker-based build environment (instead of openvz)
sudo: false

# Select JDKs >= Java 7 for testing
language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

# Test execution
install: true
script: "mvn -e -q clean compile test > /dev/null"
